baseURL = "http://berthels.co.uk"
languageCode = "en-gb"
title = "Bits and Pieces"
theme = "hugo-dusk"

copyright = "Copyright 2017. All rights reserved."
canonifyurls = true
paginate = 10

[author]
name = "John Berthels"

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

#[params.meta]
#  keywords = "blog, tech"
#  description = "Personal blog."

[params]
  github = "jbert"
  twitter = "jberthels"
  linkedin = "johnberthels"
  email = "john.berthels@gmail.com"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
